title: Home
icon: mdi:home
panel: true
views:
  - badges:
      - binary_sensor.updater
      - person.swakes
      - sensor.network_out_eth0
      - sensor.network_in_eth0
      - sensor.ipv4_address_eth0
      - sensor.disk_use_percent_home
      - sensor.memory_free
      - sensor.processor_use
      - sensor.daylight
      - sensor.transmission_started_torrents
      - sensor.plex
      - sensor.transmission_active_torrents
      - sensor.transmission_completed_torrents
      - sensor.transmission_status
      - sensor.transmission_paused_torrents
      - sensor.transmission_down_speed
      - sensor.transmission_total_torrents
      - sensor.transmission_up_speed
      - sensor.unifi_gateway_3_packets_sent
      - sensor.unifi_gateway_3_kbyte_sec_received
      - sensor.unifi_gateway_3_packets_sec_sent
      - sensor.unifi_gateway_3_packets_sec_received
      - sensor.unifi_gateway_3_packets_received
      - sensor.unifi_gateway_3_kbyte_sec_sent
      - sensor.unifi_gateway_3_bytes_sent
      - sensor.unifi_gateway_3_bytes_received
      - sun.sun
cards:
  - type: custom:layout-card
    layout: vertical
    #max_width: [40%, 300px, 20%]
    column_num: 3
    cards:
      
      - type: picture-entity
        entity: binary_sensor.hp20
        state_image:
          "on": /local/home.png
          "off": /local/away.png
      - entity: weather.home
        type: weather-forecast
      - type: custom:atomic-calendar
        title: Calendar
        enableModeChange: true
        defaultMode: 2
        CalEventIcon1Filter: birthday
        CalEventIcon2Filter: waste,bills
        entities:
          - entity: !secret emailcal
            type: icon1,icon2
      - break
      - type: custom:banner-card
        background: "#00537a"
        heading: "\U0001F68C Buses"
        row_size: 2
        entities:
              - sensor.next_bus_to_nottingham
              - sensor.next_bus_route
              - sensor.next_bus_estimated
              - sensor.next_bus_scheduled
      - type: custom:banner-card
        background: "#00537a"
        heading: "\U0001F697 Car"
        row_size: 3
        entities:
              - sensor.boots
              - sensor.station_street
              - sensor.hamilton
      - type: custom:swipe-card
        cards:
              - entity: camera.uvc_g3_front
                type: picture-entity
                camera_view: live
                show_state: false
                show_name: false
              - entity: camera.uvc_g3_back
                type: picture-entity
                camera_view: live
                show_state: false
                show_name: false
              - entity: camera.uvc_g3_back_2
                type: picture-entity
                camera_view: live
                show_state: false
                show_name: false
              - entity: camera.garage
                type: picture-entity
                camera_view: live
                show_state: false
                show_name: false
      - break
      - entity: media_player.playstation_4
        type: custom:mini-media-player
        background: /local/ps444.png
        source: icon
        hide:
         volume: true
         name: true
         progress: true
         controls: true
        shortcuts:
         columns: 4 # Max buttons per row
         buttons:
           - icon: mdi:playstation
             type: script
             id: script.ps4button
           - icon: mdi:menu
             type: script
             id: script.ps4option
           - icon: mdi:keyboard-return
             type: script
             id: script.ps4enter
           - icon: mdi:keyboard-backspace
             type: script
             id: script.ps4back
           - icon: mdi:chevron-left
             type: script
             id: script.ps4left
           - icon: mdi:chevron-up
             type: script
             id: script.ps4up
           - icon: mdi:chevron-down
             type: script
             id: script.ps4down
           - icon: mdi:chevron-right
             type: script
             id: script.ps4right