title: Securityv2
icon: mdi:shield
panel: true
cards:
    - type: horizontal-stack
      cards:

#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
##############################  
#*#*#*#*#*#*#*#*#*#*#*#*  
##################           *** First Column ***
#*#*#*#*#*#*#*#*#*#*#*#*
##############################
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*

         - type: vertical-stack
           cards:      
           - type: vertical-stack
             cards:            
                - type: picture-entity
                  entity: camera.uvc_g3_front
                  camera_view: live
                  show_state: false
                  show_name: false
           
           - type: vertical-stack
             cards:                 
                
                   - type: "custom:button-card"
                     color_type: label-card
                     color: rgb(16, 41, 74)
                     name: Home Security
                     styles:
                    # card:
                    #     - height: 20px
                      name:
                        - font-weight: bold
                        - font-size: 16px
                        - letter-spacing: 0.02em
                        - justify-self: center
                        - padding-left: 10px
                        #- text-transform: uppercase                
                        
           - type: horizontal-stack
             cards:
                - type: "custom:button-card"
                  color_type: card
                  entity: binary_sensor.openclose_3
                  name: Security
                  state:
                   - value: "on"
                     color: red
                     icon: mdi:alert
                     styles:
                       card:
                        - animation: blink 2s ease infinite
                   - operator: default
                     color: "#10294a"
                     icon: mdi:shield-check
                - type: "custom:button-card"
                  color_type: card
                  entity: binary_sensor.openclose_3
                  name: Fire
                  state:
                   - value: "on"
                     color: red
                     icon: mdi:alert
                     styles:
                       card:
                        - animation: blink 2s ease infinite
                   - operator: default
                     color: "#10294a"
                     icon: mdi:shield-check
                - type: "custom:button-card"
                  color_type: card
                  entity: binary_sensor.openclose_3
                  name: Water
                  state:
                   - value: "on"
                     color: red
                     icon: mdi:alert
                     styles:
                       card:
                        - animation: blink 2s ease infinite
                   - operator: default
                     color: "#10294a"
                     icon: mdi:shield-check
                - type: "custom:button-card"
                  color_type: card
                  entity: binary_sensor.openclose_3
                  name: Network
                  state:
                   - value: "on"
                     color: red
                     icon: mdi:alert
                     styles:
                       card:
                        - animation: blink 2s ease infinite
                   - operator: default
                     color: "#10294a"
                     icon: mdi:shield-check              
                     
                        
           - type: vertical-stack
             cards: 
                - type: custom:alarm_control_panel-card
                  entity: alarm_control_panel.home_alarm
                  show_keypad: true
                  #title: My Alarm
                  style: '--alarm-color-disarmed: var(--label-badge-blue);'
                  states:
                    - arm_home
                    - arm_away
                  labels:
                    ui.card.alarm_control_panel.code: Enter Ze Code
                    state.alarm_control_panel.arm_away: Away!!           
                                         
                                              
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
##############################  
#*#*#*#*#*#*#*#*#*#*#*#*  
##################           *** SECOND Column ***
#*#*#*#*#*#*#*#*#*#*#*#*
##############################
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
    
    
         - type: vertical-stack
           cards:          
            - type: picture-entity
              entity: camera.uvc_g3_back
              camera_view: live
              show_state: false
              show_name: false        
              
            - type: vertical-stack
              cards:                 
                
                   - type: "custom:button-card"
                     color_type: label-card
                     color: rgb(16, 41, 74)
                     name: Ground Floor
                     styles:
                    #   card:
                    #     - height: 20px
                      name:
                        - font-weight: bold
                        - font-size: 16px
                        - letter-spacing: 0.02em
                        - justify-self: center
                        - padding-left: 10px
                        #- text-transform: uppercase       
                   - type: "custom:button-card"
                     color_type: label-card
                     color: rgb(16, 41, 74)
                     name: Hallway
                     styles:
                      card:
                        - height: 20px
                      name:
                        # - font-weight: bold
                        - font-size: 16px
                        - letter-spacing: 0.02em
                        - justify-self: center
                        - padding-left: 10px                        
                   - type: glance
                     title: false
                     show_last_changed: true
                     columns: 3
                     entities:
                       - entity: binary_sensor.pir_sensor_4
                         name: Hallway Motion
                       - entity: binary_sensor.openclose_3
                         name: Front Door
                       - entity: binary_sensor.openclose_3
                         name: Hallway Window     
                         
######                         
                         
                   - type: "custom:button-card"
                     color_type: label-card
                     color: rgb(16, 41, 74)
                     name: Snug
                     styles:
                      card:
                        - height: 20px
                      name:
                        # - font-weight: bold
                        - font-size: 16px
                        - letter-spacing: 0.02em
                        - justify-self: center
                        - padding-left: 10px                        
                   - type: glance
                     title: false
                     show_last_changed: true
                     columns: 3
                     entities:
                       - entity: binary_sensor.pir_sensor_4
                         name: Motion
                       - entity: binary_sensor.openclose_3
                         name: Door
                       - entity: binary_sensor.openclose_3
                         name: Window     
                         
######                         
                         
                   - type: "custom:button-card"
                     color_type: label-card
                     color: rgb(16, 41, 74)
                     name: Kitchen
                     styles:
                      card:
                        - height: 20px
                      name:
                        # - font-weight: bold
                        - font-size: 16px
                        - letter-spacing: 0.02em
                        - justify-self: center
                        - padding-left: 10px                        
                   - type: glance
                     title: false
                     show_last_changed: true
                     #show_icon: false
                     columns: 3
                     entities:
                       - entity: binary_sensor.pir_sensor_4
                         name: Motion
                       - entity: binary_sensor.openclose_3
                         name: Door
                       - entity: binary_sensor.openclose_3
                         name: Patio Door
                       - entity: binary_sensor.openclose_3
                         name: Windows                           
                       - entity: binary_sensor.openclose_3
                         name: Cat Flap                          

#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
##############################  
#*#*#*#*#*#*#*#*#*#*#*#*  
##################           *** THIRD Column ***
#*#*#*#*#*#*#*#*#*#*#*#*
##############################
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*  


         - type: vertical-stack
           cards:          
            - type: picture-entity
              entity: camera.uvc_g3_back_2
              camera_view: live    
              show_state: false
              show_name: false                                    

            - type: vertical-stack
              cards:                 
                
                   - type: "custom:button-card"
                     color_type: label-card
                     color: rgb(16, 41, 74)
                     name: First Floor
                     styles:
                    #   card:
                    #     - height: 20px
                      name:
                        - font-weight: bold
                        - font-size: 16px
                        - letter-spacing: 0.02em
                        - justify-self: center
                        - padding-left: 10px
                        #- text-transform: uppercase
                   - type: "custom:button-card"
                     color_type: label-card
                     color: rgb(16, 41, 74)
                     name: Landing
                     styles:
                      card:
                        - height: 20px
                      name:
                        # - font-weight: bold
                        - font-size: 16px
                        - letter-spacing: 0.02em
                        - justify-self: center
                        - padding-left: 10px                        
                   - type: glance
                     title: false
                     show_last_changed: true
                     #columns: 3
                     entities:
                       - entity: binary_sensor.pir_sensor_4
                         name: Motion
                         
######                         
                         
                   - type: "custom:button-card"
                     color_type: label-card
                     color: rgb(16, 41, 74)
                     name: Living Room
                     styles:
                      card:
                        - height: 20px
                      name:
                        # - font-weight: bold
                        - font-size: 16px
                        - letter-spacing: 0.02em
                        - justify-self: center
                        - padding-left: 10px                        
                   - type: glance
                     title: false
                     show_last_changed: true
                     columns: 3
                     entities:
                       - entity: binary_sensor.pir_sensor_4
                         name: Motion
                       - entity: binary_sensor.openclose_3
                         name: Door
                       - entity: binary_sensor.openclose_3
                         name: Window     
                         
######                         
                         
                   - type: "custom:button-card"
                     color_type: label-card
                     color: rgb(16, 41, 74)
                     name: Guest Bedroom
                     styles:
                      card:
                        - height: 20px
                      name:
                        # - font-weight: bold
                        - font-size: 16px
                        - letter-spacing: 0.02em
                        - justify-self: center
                        - padding-left: 10px                        
                   - type: glance
                     title: false
                     show_last_changed: true
                     #show_icon: false
                     #columns: 3
                     entities:
                       - entity: binary_sensor.openclose_3
                         name: Door
                         
#######                         
                        
                   - type: "custom:button-card"
                     color_type: label-card
                     color: rgb(16, 41, 74)
                     name: Guest Bathroom
                     styles:
                      card:
                        - height: 20px
                      name:
                        # - font-weight: bold
                        - font-size: 16px
                        - letter-spacing: 0.02em
                        - justify-self: center
                        - padding-left: 10px                        
                   - type: glance
                     title: false
                     show_last_changed: true
                     #show_icon: false
                     #columns: 3
                     entities:
                       - entity: binary_sensor.openclose_3
                         name: Door
                         
                         
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*
##############################  
#*#*#*#*#*#*#*#*#*#*#*#*  
##################           *** FORTH Column ***
#*#*#*#*#*#*#*#*#*#*#*#*
##############################
#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*


         - type: vertical-stack
           cards:          
            - type: picture-entity
              entity: camera.garage
              camera_view: live    
              show_state: false
              show_name: false  


            - type: vertical-stack
              cards:                 
                
                   - type: "custom:button-card"
                     color_type: label-card
                     color: rgb(16, 41, 74)
                     name: Second Floor
                     styles:
                    #   card:
                    #     - height: 20px
                      name:
                        # - font-weight: bold
                        - font-size: 16px
                        - letter-spacing: 0.02em
                        - justify-self: center
                        - padding-left: 10px
                        #- text-transform: uppercase
