homeassistant:
  # Name of the location where Home Assistant is running
  name: SWAKES
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 10
  unit_system: metric
  time_zone: Europe/London

  
  packages: !include_dir_named components/packages
  #automation: !include_dir_named components/automation

hacs:
  token: !secret token
  sidepanel_title: Community